-- ========================================
-- MISE À JOUR DES GRADES DEPUIS LE CSV
-- ========================================
-- 
-- Ce script a été généré automatiquement depuis Liste-du-Personel-_1_.csv
-- Date de génération : 2025-11-06T12:18:38.203Z
-- 
-- Grades disponibles :
-- A3 → id=37, A4 → id=38, A5 → id=39, A6 → id=40, A7 → id=41
-- B1 → id=42, B2 → id=43, B3 → id=44
-- C1 → id=45, C2 → id=46
-- D1 → id=47
-- ========================================

BEGIN;

-- Statistiques AVANT mise à jour
SELECT 'AVANT MISE À JOUR' as statut;
SELECT 
    COALESCE(g.libele, 'SANS GRADE') as grade,
    COUNT(*) as nombre
FROM agents a
LEFT JOIN grades g ON a.id_grade = g.id
GROUP BY g.libele, g.id
ORDER BY g.libele;

-- Mise à jour des grades
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '201957B'; -- Grade A5
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272129B'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '434689Y'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313044S'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '366249Z'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '460997T'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '861964X'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855878B'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826255V'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889566V'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468207P'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889425Q'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '821007L'; -- Grade B1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '856634X'; -- Grade D1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '360923B'; -- Grade D1
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323311U'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '419669L'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '811076N'; -- Grade B3
UPDATE agents SET id_grade = 41, updated_at = CURRENT_TIMESTAMP WHERE matricule = '255532W'; -- Grade A7
UPDATE agents SET id_grade = 41, updated_at = CURRENT_TIMESTAMP WHERE matricule = '255533X'; -- Grade A7
UPDATE agents SET id_grade = 41, updated_at = CURRENT_TIMESTAMP WHERE matricule = '265648U'; -- Grade A7
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '275295D'; -- Grade A5
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '437484E'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337228F'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345907H'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '368215R'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '820764H'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480792S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815419P'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815488M'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '825989M'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481521F'; -- Grade B3
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '372134U'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '436116B'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464357G'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345381H'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '886661Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '902371E'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '902716Y'; -- Grade B1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '905377F'; -- Grade D1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885469Y'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323314X'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '371880C'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826175M'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826186H'; -- Grade B3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885397Q'; -- Grade A3
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323944X'; -- Grade D1
UPDATE agents SET id_grade = 41, updated_at = CURRENT_TIMESTAMP WHERE matricule = '233494K'; -- Grade A7
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272142G'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468200U'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433341Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815472L'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855864V'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855865W'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '856161V'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '265431T'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '886723P'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826009T'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481534C'; -- Grade B1
UPDATE agents SET id_grade = 46, updated_at = CURRENT_TIMESTAMP WHERE matricule = '867627T'; -- Grade C2
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291090Y'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345912V'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345906G'; -- Grade B3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '277838F'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '338383C'; -- Grade A3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272132W'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337222Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337225U'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359187D'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '452000F'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481466Q'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '483528Q'; -- Grade B1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '825998N'; -- Grade D1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '807569E'; -- Grade D1
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359184A'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468852D'; -- Grade B3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '307354Q'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345662J'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832839M'; -- Grade B3
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '372229K'; -- Grade C1
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '358599R'; -- Grade A5
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297584N'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304895V'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '402854W'; -- Grade A3
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '314826Q'; -- Grade A5
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855854T'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323854V'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '874067U'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855890U'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323855W'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '435599P'; -- Grade A3
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482009T'; -- Grade D1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '307251R'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '484367X'; -- Grade B3
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '312892R'; -- Grade A5
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '925925G'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826301U'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855875Y'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359190L'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815507Q'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855467X'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855816M'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855818X'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855852Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855847U'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '877509G'; -- Grade B1
UPDATE agents SET id_grade = 46, updated_at = CURRENT_TIMESTAMP WHERE matricule = '268184F'; -- Grade C2
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481418Q'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '467173T'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297582L'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815433D'; -- Grade B3
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '483698T'; -- Grade C1
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297577W'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291171Z'; -- Grade B3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '491347S'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855859G'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '825999P'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '886194E'; -- Grade B3
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885532F'; -- Grade D1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '467389C'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '467423N'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482306Z'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827779B'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827781N'; -- Grade B3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827810P'; -- Grade A3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481073R'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '886296L'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '886369C'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '890118Z'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481638U'; -- Grade B1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '420373G'; -- Grade D1
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313054U'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359136H'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815459X'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855829S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855825N'; -- Grade B3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323845U'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480594L'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480817K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337223S'; -- Grade B3
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '293402U'; -- Grade A5
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323830Z'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827831G'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834867K'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '365770W'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359181F'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337231S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '493835E'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810016M'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '857121N'; -- Grade B1
UPDATE agents SET id_grade = 40, updated_at = CURRENT_TIMESTAMP WHERE matricule = '327124M'; -- Grade A6
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '280155A'; -- Grade A5
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '467560B'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855832M'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '871253G'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '365484V'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313048E'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '319370X'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433903N'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304886U'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855874X'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889388B'; -- Grade B1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '887494C'; -- Grade C1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827768G'; -- Grade D1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '277839G'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337229G'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313039V'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '368217K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855828Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481434G'; -- Grade B3
UPDATE agents SET id_grade = 40, updated_at = CURRENT_TIMESTAMP WHERE matricule = '312887L'; -- Grade A6
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291611S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433865P'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433879V'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482018K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815454J'; -- Grade B3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '821059X'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815476Q'; -- Grade B3
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '265759T'; -- Grade A5
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297586Q'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337226V'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481942M'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815497E'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323836K'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480631Y'; -- Grade B3
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '201560R'; -- Grade A5
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855860D'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '820545W'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '808046E'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '806844Z'; -- Grade B1
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '286956X'; -- Grade A5
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323833Q'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '368216J'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827828M'; -- Grade B3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323834R'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323840B'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359185B'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464162V'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815504M'; -- Grade B3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '492302X'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855841W'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '858378Y'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826007R'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297590Y'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359188N'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827817A'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832911D'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '251283H'; -- Grade A4
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '487322M'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '867562S'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304885T'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '368214Q'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889093P'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '876799H'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826157K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855826P'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481626Q'; -- Grade B1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '887502L'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '887689X'; -- Grade C1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826011C'; -- Grade D1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '908887T'; -- Grade D1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815436G'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852207G'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852240L'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '865786Z'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '319371L'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '284526N'; -- Grade A3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481934D'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855888W'; -- Grade B1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481904Q'; -- Grade D1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '338288M'; -- Grade D1
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '275045D'; -- Grade A5
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '233613Z'; -- Grade A5
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '355154F'; -- Grade B3
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '390278T'; -- Grade C1
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '456919U'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852135P'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '865752E'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '865780F'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '865813L'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855883R'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '897985A'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '806868H'; -- Grade B1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '890209M'; -- Grade C1
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '372652K'; -- Grade A5
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '442433P'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '320381C'; -- Grade B3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '344925Z'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '473683Z'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323856X'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '390102C'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '379660E'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272140J'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345913W'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313055V'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323848F'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480710B'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482019L'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815486B'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834105Q'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815460U'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855838T'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '874645C'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '469466B'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855877S'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826002L'; -- Grade B1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '421314J'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468225G'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468562A'; -- Grade C1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '802422N'; -- Grade D1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291178G'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852291U'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304888E'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304889F'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323829U'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337230D'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '386459H'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '435328W'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480566X'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480684W'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815421H'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815435F'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815491G'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834142L'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855839U'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889312W'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '856590Y'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889628B'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '874813M'; -- Grade B1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '469887S'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481572J'; -- Grade C1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482868U'; -- Grade D1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291182M'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '802321Y'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852286X'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '434616N'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433404J'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447591K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832904P'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855830X'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855846T'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '474937Q'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '470972B'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885624K'; -- Grade B1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468537Z'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481445K'; -- Grade C1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '231138T'; -- Grade D1
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '265962F'; -- Grade A5
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '803532M'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313043Z'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323827J'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323831N'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482328W'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304892S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323846V'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359182G'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447958A'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464165Y'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480545S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834359D'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855822K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855843Y'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855868H'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855891R'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '467987L'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '483707U'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '875722S'; -- Grade B1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304882Y'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '384378M'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323853U'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323843S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447582J'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464167S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480581P'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481978Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815423B'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832859Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834958W'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855372F'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855848D'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855882Q'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855886L'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855889X'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '857718C'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '875678N'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855857W'; -- Grade B1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481393P'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855855U'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272128A'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '871901T'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815446J'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '870454D'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323838V'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323857Y'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345914X'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433356Y'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433391L'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447587P'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '418949C'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464159A'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815445R'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '830080W'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832891A'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855863U'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885584C'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855842X'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '904690D'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852136Q'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291177X'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313040A'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464176T'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464180U'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '470032Y'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480564V'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815455K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815664U'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832864N'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832874Q'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832919M'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855833N'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889097K'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '874642H'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '498943X'; -- Grade B1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481384N'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827809T'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291174U'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '435225P'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815499Q'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345910F'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '418988U'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '475706A'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855884J'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447589Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480503Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481901M'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481983F'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '495974K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '898664G'; -- Grade B3
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '418951W'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '334707D'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815669H'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '820825P'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '866768P'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272130G'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345916Z'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '361854B'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480587M'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810584L'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855850B'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '858955B'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '820542T'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '470988C'; -- Grade B3
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481623M'; -- Grade D1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304896W'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480601B'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855469H'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855858F'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '350234N'; -- Grade B3
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '469479Q'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481392N'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '830131R'; -- Grade C1
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '158733E'; -- Grade A5
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '483686P'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '803534P'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852132L'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313045T'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323837L'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855872V'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323849G'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464171W'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480586L'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480692W'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480743G'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827945J'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '830050F'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832854L'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834086G'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834133B'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855853S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827449Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '273520G'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855837J'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481455M'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '901902T'; -- Grade B1
UPDATE agents SET id_grade = 46, updated_at = CURRENT_TIMESTAMP WHERE matricule = '349302W'; -- Grade C2
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '315994J'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297630F'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815474N'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852217Z'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433357Z'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '467420X'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855831L'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480518X'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '816080L'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810032M'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '874661C'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '874803U'; -- Grade B1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482932C'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291176W'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815478S'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '888935N'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480624Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481961Q'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815475P'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815501J'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855835Q'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481494D'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297585P'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852197N'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481893D'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855871U'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885472K'; -- Grade B1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '483687Q'; -- Grade C1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313773H'; -- Grade D1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272135Z'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815418N'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297579G'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359178T'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '387981N'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481925C'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481962R'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481976P'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '418948B'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885708G'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826153P'; -- Grade B1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468090H'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481412A'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482004N'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '897703X'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834755S'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '277841A'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815431B'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '485169S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464166Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480731U'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855861S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855862T'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855873W'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826154Q'; -- Grade B3
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481590R'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '420435P'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '357771K'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852231X'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '319399R'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '908662Q'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '805019Y'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447557Y'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480679Q'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855879C'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '418984Q'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468402B'; -- Grade B1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '371987T'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481413B'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481526C'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826158U'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '902807V'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '246394B'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815449V'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433367T'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '434033H'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481049Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827826B'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855817N'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815490K'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '856181J'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481935E'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '819118V'; -- Grade B1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815477R'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272133X'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481390Y'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '803457S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815447K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815456L'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313047V'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855824M'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '820543U'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855880S'; -- Grade B3
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '491244T'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855834P'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '400817T'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '803543Y'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '875950B'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297588S'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359186C'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855856V'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480632Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481541K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832885C'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855845S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815427F'; -- Grade B3
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481383M'; -- Grade C1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481566L'; -- Grade D1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '887249D'; -- Grade D1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291179H'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '357870K'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464170H'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464173Y'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815481E'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827822F'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827824H'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272141F'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815473M'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447559A'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481064Q'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855887M'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272139D'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815437H'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '865406V'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464161U'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480638F'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480695Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482017A'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815462J'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815468Y'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '830036M'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '470991X'; -- Grade B1
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '470054E'; -- Grade B1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '483237L'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '856191L'; -- Grade C1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '471757G'; -- Grade D1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304891Z'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852280D'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447572X'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464178D'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '490020V'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855823L'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855851Y'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '490894K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826156J'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '886245Y'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '876947V'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291183N'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855866X'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481905R'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815480R'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855450A'; -- Grade B3
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481542L'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855849E'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291175V'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815434E'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481640A'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815492H'; -- Grade B1
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '358754T'; -- Grade A5
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272134Y'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '318251K'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '864879D'; -- Grade B3
UPDATE agents SET id_grade = 40, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291061W'; -- Grade A6
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '357504H'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815458W'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815489N'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852269M'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304890C'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '305831V'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '386604B'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433382K'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '466992Q'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '874654D'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482246U'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '385534K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447588Y'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480523L'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480694Y'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480709P'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815426E'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815451P'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '819354H'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827829N'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832853K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832886D'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855867Y'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855881P'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815461R'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826001K'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827419K'; -- Grade B1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826005P'; -- Grade D1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297591M'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815448U'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359189P'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885392K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464168B'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481505Q'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855869A'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '820547Y'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '471018X'; -- Grade B1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481207V'; -- Grade D1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313051Z'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852216Y'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827761Z'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323835J'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464179E'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480580S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815420L'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855820V'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889085P'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '419036M'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855844Z'; -- Grade B3
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323197K'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889420X'; -- Grade C1
UPDATE agents SET id_grade = 40, updated_at = CURRENT_TIMESTAMP WHERE matricule = '231462Y'; -- Grade A6
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815482F'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815422A'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323850D'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855885K'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482010P'; -- Grade B3
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481500X'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304898G'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '863462S'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '485206Y'; -- Grade B1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '887753W'; -- Grade C1
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '890060E'; -- Grade C1
UPDATE agents SET id_grade = 40, updated_at = CURRENT_TIMESTAMP WHERE matricule = '251279U'; -- Grade A6
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '396544Y'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '809988D'; -- Grade A4
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '285815R'; -- Grade A5
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '866514R'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '315928X'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '350428R'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815450S'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855827Q'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '821115C'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '314003T'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '886292Q'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '888832P'; -- Grade B3
UPDATE agents SET id_grade = 42, updated_at = CURRENT_TIMESTAMP WHERE matricule = '811666S'; -- Grade B1
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359729T'; -- Grade D1
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '159015T'; -- Grade A5
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '821439R'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '813575R'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '245090H'; -- Grade A4
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '265045B'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827422E'; -- Grade B3
UPDATE agents SET id_grade = 46, updated_at = CURRENT_TIMESTAMP WHERE matricule = '298230P'; -- Grade C2
UPDATE agents SET id_grade = 47, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313290A'; -- Grade D1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810493R'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827978T'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '809995U'; -- Grade B3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313050C'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345915Y'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '307272N'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337227W'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810020V'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810075Y'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827511F'; -- Grade B3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323842Z'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481519M'; -- Grade B3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304899H'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '284351E'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '865713X'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '305872E'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291172S'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304893T'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323828T'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '251272M'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291170C'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272131V'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304884S'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810000A'; -- Grade B3
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291184P'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '361146D'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304897X'; -- Grade A3
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345909K'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359179U'; -- Grade B3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810021J'; -- Grade B3
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '807762F'; -- Grade C1
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '365485W'; -- Grade A5
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '389796E'; -- Grade A5
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '206234B'; -- Grade A5
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '282337W'; -- Grade A5
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '203254L'; -- Grade A5
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '306629K'; -- Grade A5
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '237252B'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '870807G'; -- Grade A3
UPDATE agents SET id_grade = 45, updated_at = CURRENT_TIMESTAMP WHERE matricule = '483689S'; -- Grade C1
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885394M'; -- Grade A4
UPDATE agents SET id_grade = 37, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885447J'; -- Grade A3
UPDATE agents SET id_grade = 44, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827509W'; -- Grade B3
UPDATE agents SET id_grade = 40, updated_at = CURRENT_TIMESTAMP WHERE matricule = '355870R'; -- Grade A6
UPDATE agents SET id_grade = 39, updated_at = CURRENT_TIMESTAMP WHERE matricule = '290488B'; -- Grade A5
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '343470L'; -- Grade A4
UPDATE agents SET id_grade = 38, updated_at = CURRENT_TIMESTAMP WHERE matricule = '162855V'; -- Grade A4

-- Statistiques APRÈS mise à jour
SELECT 'APRÈS MISE À JOUR' as statut;
SELECT 
    COALESCE(g.libele, 'SANS GRADE') as grade,
    COUNT(*) as nombre
FROM agents a
LEFT JOIN grades g ON a.id_grade = g.id
GROUP BY g.libele, g.id
ORDER BY g.libele;

-- Résumé
SELECT '========================================' as separation;
SELECT 'RÉSUMÉ DE LA MISE À JOUR DES GRADES' as titre;
SELECT '========================================' as separation;
SELECT 'Total mises à jour générées' as description, 740 as nombre;
SELECT 'Grade A3' as description, 117 as nombre;
SELECT 'Grade A4' as description, 122 as nombre;
SELECT 'Grade A5' as description, 25 as nombre;
SELECT 'Grade A6' as description, 6 as nombre;
SELECT 'Grade A7' as description, 4 as nombre;
SELECT 'Grade B1' as description, 51 as nombre;
SELECT 'Grade B3' as description, 335 as nombre;
SELECT 'Grade C1' as description, 50 as nombre;
SELECT 'Grade C2' as description, 4 as nombre;
SELECT 'Grade D1' as description, 26 as nombre;

-- IMPORTANT : Décommentez la ligne suivante pour VALIDER les changements
COMMIT;

-- Ou décommentez celle-ci pour ANNULER
-- ROLLBACK;

-- Les changements ont été validés automatiquement
