-- ========================================
-- MISE À JOUR DES CATÉGORIES DEPUIS LE CSV
-- ========================================
-- 
-- Ce script a été généré automatiquement depuis Liste-du-Personel-_1_.csv
-- Date de génération : 2025-11-06T12:08:51.776Z
-- 
-- Catégories :
-- A → id=5
-- B → id=6
-- C → id=9
-- D → id=8
-- ========================================

BEGIN;

-- Statistiques AVANT mise à jour
SELECT 'AVANT MISE À JOUR' as statut;
SELECT 
    COALESCE(c.libele, 'SANS CATÉGORIE') as categorie,
    COUNT(*) as nombre
FROM agents a
LEFT JOIN categories c ON a.id_categorie = c.id
GROUP BY c.libele
ORDER BY 
    CASE 
        WHEN c.libele = 'A' THEN 1
        WHEN c.libele = 'B' THEN 2
        WHEN c.libele = 'C' THEN 3
        WHEN c.libele = 'D' THEN 4
        ELSE 5
    END;

-- Mise à jour des catégories
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '201957B'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272129B'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '434689Y'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313044S'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '366249Z'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '460997T'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '861964X'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855878B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826255V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889566V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468207P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889425Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '821007L'; -- Catégorie B
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '856634X'; -- Catégorie D
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '360923B'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323311U'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '419669L'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '811076N'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '255532W'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '255533X'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '265648U'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '275295D'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '437484E'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337228F'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345907H'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '368215R'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '820764H'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480792S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815419P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815488M'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '825989M'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481521F'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '372134U'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '436116B'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464357G'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345381H'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '886661Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '902371E'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '902716Y'; -- Catégorie B
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '905377F'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885469Y'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323314X'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '371880C'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826175M'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826186H'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885397Q'; -- Catégorie A
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323944X'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '233494K'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272142G'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468200U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433341Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815472L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855864V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855865W'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '856161V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '265431T'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '886723P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826009T'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481534C'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '867627T'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291090Y'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345912V'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345906G'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '277838F'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '338383C'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272132W'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337222Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337225U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359187D'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '452000F'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481466Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '483528Q'; -- Catégorie B
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '825998N'; -- Catégorie D
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '807569E'; -- Catégorie D
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359184A'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468852D'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '307354Q'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345662J'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832839M'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '372229K'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '358599R'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297584N'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304895V'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '402854W'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '314826Q'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855854T'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323854V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '874067U'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855890U'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323855W'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '435599P'; -- Catégorie A
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482009T'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '307251R'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '484367X'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '312892R'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '925925G'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826301U'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855875Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359190L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815507Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855467X'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855816M'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855818X'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855852Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855847U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '877509G'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '268184F'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481418Q'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '467173T'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297582L'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815433D'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '483698T'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297577W'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291171Z'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '491347S'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855859G'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '825999P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '886194E'; -- Catégorie B
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885532F'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '467389C'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '467423N'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482306Z'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827779B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827781N'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827810P'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481073R'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '886296L'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '886369C'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '890118Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481638U'; -- Catégorie B
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '420373G'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313054U'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359136H'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815459X'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855829S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855825N'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323845U'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480594L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480817K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337223S'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '293402U'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323830Z'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827831G'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834867K'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '365770W'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359181F'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337231S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '493835E'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810016M'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '857121N'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '327124M'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '280155A'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '467560B'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855832M'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '871253G'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '365484V'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313048E'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '319370X'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433903N'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304886U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855874X'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889388B'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '887494C'; -- Catégorie C
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827768G'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '277839G'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337229G'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313039V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '368217K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855828Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481434G'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '312887L'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291611S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433865P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433879V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482018K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815454J'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '821059X'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815476Q'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '265759T'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297586Q'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337226V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481942M'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815497E'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323836K'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480631Y'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '201560R'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855860D'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '820545W'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '808046E'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '806844Z'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '286956X'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323833Q'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '368216J'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827828M'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323834R'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323840B'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359185B'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464162V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815504M'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '492302X'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855841W'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '858378Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826007R'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297590Y'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359188N'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827817A'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832911D'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '251283H'; -- Catégorie A
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '487322M'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '867562S'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304885T'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '368214Q'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889093P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '876799H'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826157K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855826P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481626Q'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '887502L'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '887689X'; -- Catégorie C
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826011C'; -- Catégorie D
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '908887T'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815436G'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852207G'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852240L'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '865786Z'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '319371L'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '284526N'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481934D'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855888W'; -- Catégorie B
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481904Q'; -- Catégorie D
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '338288M'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '275045D'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '233613Z'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '355154F'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '390278T'; -- Catégorie C
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '456919U'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852135P'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '865752E'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '865780F'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '865813L'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855883R'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '897985A'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '806868H'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '890209M'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '372652K'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '442433P'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '320381C'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '344925Z'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '473683Z'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323856X'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '390102C'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '379660E'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272140J'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345913W'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313055V'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323848F'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480710B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482019L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815486B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834105Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815460U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855838T'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '874645C'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '469466B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855877S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826002L'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '421314J'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468225G'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468562A'; -- Catégorie C
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '802422N'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291178G'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852291U'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304888E'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304889F'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323829U'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337230D'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '386459H'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '435328W'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480566X'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480684W'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815421H'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815435F'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815491G'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834142L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855839U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889312W'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '856590Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889628B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '874813M'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '469887S'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481572J'; -- Catégorie C
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482868U'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291182M'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '802321Y'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852286X'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '434616N'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433404J'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447591K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832904P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855830X'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855846T'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '474937Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '470972B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885624K'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468537Z'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481445K'; -- Catégorie C
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '231138T'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '265962F'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '803532M'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313043Z'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323827J'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323831N'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482328W'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304892S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323846V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359182G'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447958A'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464165Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480545S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834359D'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855822K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855843Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855868H'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855891R'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '467987L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '483707U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '875722S'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304882Y'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '384378M'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323853U'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323843S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447582J'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464167S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480581P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481978Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815423B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832859Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834958W'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855372F'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855848D'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855882Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855886L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855889X'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '857718C'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '875678N'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855857W'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481393P'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855855U'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272128A'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '871901T'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815446J'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '870454D'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323838V'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323857Y'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345914X'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433356Y'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433391L'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447587P'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '418949C'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464159A'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815445R'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '830080W'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832891A'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855863U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885584C'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855842X'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '904690D'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852136Q'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291177X'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313040A'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464176T'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464180U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '470032Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480564V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815455K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815664U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832864N'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832874Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832919M'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855833N'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889097K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '874642H'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '498943X'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481384N'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827809T'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291174U'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '435225P'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815499Q'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345910F'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '418988U'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '475706A'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855884J'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447589Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480503Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481901M'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481983F'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '495974K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '898664G'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '418951W'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '334707D'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815669H'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '820825P'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '866768P'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272130G'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345916Z'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '361854B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480587M'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810584L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855850B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '858955B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '820542T'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '470988C'; -- Catégorie B
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481623M'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304896W'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480601B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855469H'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855858F'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '350234N'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '469479Q'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481392N'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '830131R'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '158733E'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '483686P'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '803534P'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852132L'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313045T'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323837L'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855872V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323849G'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464171W'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480586L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480692W'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480743G'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827945J'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '830050F'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832854L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834086G'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834133B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855853S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827449Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '273520G'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855837J'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481455M'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '901902T'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '349302W'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '315994J'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297630F'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815474N'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852217Z'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433357Z'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '467420X'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855831L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480518X'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '816080L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810032M'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '874661C'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '874803U'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482932C'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291176W'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815478S'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '888935N'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480624Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481961Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815475P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815501J'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855835Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481494D'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297585P'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852197N'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481893D'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855871U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885472K'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '483687Q'; -- Catégorie C
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313773H'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272135Z'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815418N'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297579G'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359178T'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '387981N'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481925C'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481962R'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481976P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '418948B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885708G'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826153P'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468090H'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481412A'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482004N'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '897703X'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '834755S'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '277841A'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815431B'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '485169S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464166Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480731U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855861S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855862T'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855873W'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826154Q'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481590R'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '420435P'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '357771K'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852231X'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '319399R'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '908662Q'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '805019Y'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447557Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480679Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855879C'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '418984Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '468402B'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '371987T'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481413B'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481526C'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826158U'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '902807V'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '246394B'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815449V'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433367T'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '434033H'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481049Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827826B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855817N'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815490K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '856181J'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481935E'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '819118V'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815477R'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272133X'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481390Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '803457S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815447K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815456L'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313047V'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855824M'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '820543U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855880S'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '491244T'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855834P'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '400817T'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '803543Y'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '875950B'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297588S'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359186C'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855856V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480632Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481541K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832885C'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855845S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815427F'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481383M'; -- Catégorie C
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481566L'; -- Catégorie D
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '887249D'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291179H'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '357870K'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464170H'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464173Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815481E'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827822F'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827824H'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272141F'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815473M'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447559A'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481064Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855887M'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272139D'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815437H'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '865406V'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464161U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480638F'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480695Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482017A'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815462J'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815468Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '830036M'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '470991X'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '470054E'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '483237L'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '856191L'; -- Catégorie C
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '471757G'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304891Z'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852280D'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447572X'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464178D'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '490020V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855823L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855851Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '490894K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826156J'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '886245Y'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '876947V'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291183N'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855866X'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481905R'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815480R'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855450A'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481542L'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855849E'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291175V'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815434E'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481640A'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815492H'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '358754T'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272134Y'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '318251K'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '864879D'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291061W'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '357504H'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815458W'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815489N'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852269M'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304890C'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '305831V'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '386604B'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '433382K'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '466992Q'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '874654D'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482246U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '385534K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '447588Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480523L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480694Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480709P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815426E'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815451P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '819354H'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827829N'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832853K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '832886D'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855867Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855881P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815461R'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826001K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827419K'; -- Catégorie B
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '826005P'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '297591M'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815448U'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359189P'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885392K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464168B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481505Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855869A'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '820547Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '471018X'; -- Catégorie B
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481207V'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313051Z'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '852216Y'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827761Z'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323835J'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '464179E'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '480580S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815420L'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855820V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889085P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '419036M'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855844Z'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323197K'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '889420X'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '231462Y'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815482F'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815422A'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323850D'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855885K'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '482010P'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481500X'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304898G'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '863462S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '485206Y'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '887753W'; -- Catégorie C
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '890060E'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '251279U'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '396544Y'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '809988D'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '285815R'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '866514R'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '315928X'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '350428R'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '815450S'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '855827Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '821115C'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '314003T'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '886292Q'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '888832P'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '811666S'; -- Catégorie B
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359729T'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '159015T'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '821439R'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '813575R'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '245090H'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '265045B'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827422E'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '298230P'; -- Catégorie C
UPDATE agents SET id_categorie = 8, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313290A'; -- Catégorie D
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810493R'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827978T'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '809995U'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '313050C'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345915Y'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '307272N'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '337227W'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810020V'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810075Y'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827511F'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323842Z'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '481519M'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304899H'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '284351E'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '865713X'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '305872E'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291172S'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304893T'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '323828T'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '251272M'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291170C'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '272131V'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304884S'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810000A'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '291184P'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '361146D'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '304897X'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '345909K'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '359179U'; -- Catégorie B
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '810021J'; -- Catégorie B
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '807762F'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '365485W'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '389796E'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '206234B'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '282337W'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '203254L'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '306629K'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '237252B'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '870807G'; -- Catégorie A
UPDATE agents SET id_categorie = 9, updated_at = CURRENT_TIMESTAMP WHERE matricule = '483689S'; -- Catégorie C
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885394M'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '885447J'; -- Catégorie A
UPDATE agents SET id_categorie = 6, updated_at = CURRENT_TIMESTAMP WHERE matricule = '827509W'; -- Catégorie B
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '355870R'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '290488B'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '343470L'; -- Catégorie A
UPDATE agents SET id_categorie = 5, updated_at = CURRENT_TIMESTAMP WHERE matricule = '162855V'; -- Catégorie A

-- Statistiques APRÈS mise à jour
SELECT 'APRÈS MISE À JOUR' as statut;
SELECT 
    COALESCE(c.libele, 'SANS CATÉGORIE') as categorie,
    COUNT(*) as nombre
FROM agents a
LEFT JOIN categories c ON a.id_categorie = c.id
GROUP BY c.libele
ORDER BY 
    CASE 
        WHEN c.libele = 'A' THEN 1
        WHEN c.libele = 'B' THEN 2
        WHEN c.libele = 'C' THEN 3
        WHEN c.libele = 'D' THEN 4
        ELSE 5
    END;

-- Résumé
SELECT '========================================' as separation;
SELECT 'RÉSUMÉ DE LA MISE À JOUR' as titre;
SELECT '========================================' as separation;
SELECT 'Total mises à jour générées' as description, 740 as nombre;
SELECT 'Catégorie A' as description, 274 as nombre;
SELECT 'Catégorie B' as description, 386 as nombre;
SELECT 'Catégorie C' as description, 54 as nombre;
SELECT 'Catégorie D' as description, 26 as nombre;

-- IMPORTANT : Décommentez la ligne suivante pour VALIDER les changements
COMMIT;

-- Ou décommentez celle-ci pour ANNULER
-- ROLLBACK;

-- Les changements ont été validés automatiquement
